### ISSUE TITLE
Lua Error:  un-finished bytes (len 639 at offset 872)

### ISSUE THREAD

**Issue by haitor888** [starwing/lua-protobuf#103]
Lua Error:  un-finished bytes (len 639 at offset 872)

**Comment by haitor888** [comment]
000000010A02080012CF060AA90208F5CF808008121135333131353233303236333337383530371A0867656F726765687520002803380040044881809C1F50BF9991E90558006000A001BBD4CDEB05A80100B001E29FA2EB05F001019002B0C7FFD3918191EA509802B0C7FFD3918191EA50A2020410015001AA02AB0108E5DFCDEB05108480C080B0FADBB95D28848040620608EEC6B99B066A1B0A04080110690A05080110C9010A05080110CC010A05080110D90472510A2C08691800221C08DC8D0608A0AA1208A0AA12088CAA1208929C0C08E78D06088F8E06281030013801400150010A0708C901300138010A0708CC01300138010A0708D904300138010A02080A0A02080B780080018F4E8801019001BBCAF4D307980100A00101A80169C00169C80100B20200B80200C00200CA0200D0020012B20108F4AC0310B8172001388480C080B0FADBB95D8A02114368696E65736553696D706C6966696564A00201C00264D00200D80264E00203F002288003009A030A7A685F48616E735F434EA00301A80302E00369E80303F00380E5A5CC028004698804019004019A040C0A0A08691001380140004800A00401A80400B20405080610ED02B20405080510A401B20405080410BF01B2040408071063B204040803102EB80400C20400C80402D00402D80406F004031A2A08021A120808120E080110D29A0C180120BF9991E9051A120803120E080210D19A0C180120F0A192E905222512230A210800120F10FFFFFFFFFFFFFFFFFF01220028071205100128C7011205100128C8012A5A1A100A060832100128000A0608311002280022002A0032003A400A0608A9C00210000A0608AAC00210010A0608ABC00210020A0608ACC00210030A0608ADC00210040A0608AEC00210050A0608AFC00210060A0608B0C00210073A190A04080A101E0A05080B10B8030A04082810010A040827100042005A0B3880B7B1EB05400048D40262920108EA07120A08BF9991E90510001801120B08BF9991E905100018E707120B08BF9991E905100018E807120B08BF9991E905100018E907120B08BF9991E905100018EA07120B08BF9991E905100018EB07120B08BF9991E905100018ED07120B08BF9991E905100018EE07120B08BF9991E905100018EF07120B08BF9991E905100018F0071801220A08BF9991E9051000180118F2E0CDEB05200032003AFF040A1D080E1A002215506C617965724E616D654C656E6774684C696D697428210A9A0108001A80013638333739303132312D6B55386E4D51326F4334345A6554734354686839364E4D6B424B4C74496370733B3139363833383038372D3676486E37665A5867486365703342702D354C63446E6C6F534E4332776E586A3B3438303032333635312D306A516D52375263564C51365F684265486279546267767261453876306A4C7A2211515147726F75705F4A6F696E5F4C69737428480A1A08001A002212506C61745F496E766974655F456E61626C6528530A69080010011A4C23536572766572732077696C6C20626520646F776E2061742030303A3030206F6E20417567757374203874682E204D617463686D616B696E6720686173206265656E2064697361626C65642E2213436C6F736553657276657254696D65496E666F28750A1B080A1A00221243

**Comment by haitor888** [comment]
local data2 = assert(pb.decode(cmdName,sourceBUF:fromhex() ))

toLog(cmdName..require "serpent".block(data2))

**Comment by hiberabyss** [comment]
Has same problem

**Comment by starwing** [comment]
your binary data has issue -- there are several zeros prefixed the message, it's not a legal protobuf message.
