### ISSUE TITLE
Obtain sizes of encoded fields 

### ISSUE THREAD

**Issue by mikevoronov** [starwing/lua-protobuf#104]
Hi, thank you for developing such a good library! 

I am writing dissector for Wireshark and using this lib to decode protobuf packets. And for me it is important to identify the sizes of fields in encoded state, because I need to assign view tree for corresponded bytes in the packets. More precisely, let's image that we have following protobuf structure:
```proto
    message Propose {
        optional bytes rand = 1;
        optional bytes pubkey = 2;
        optional string exchanges = 3;
        optional string ciphers = 4;
        optional string hashes = 5;
    }
```
Then, thanks to `lua-protobuf`, I can decode it and identify each fields and its sizes, but in encoded state size is bigger then in plain. And here I don't how to find out offset of e.g. `pubkey` in the traffic for correctly assign tree view. (example is [here](https://github.com/michaelvoronov/libp2p-dissector/blob/master/src/protocols/secio/secio.lua#L82))

Is it possible now?

**Comment by starwing** [comment]
you could try lower interface, such as pb.slice
