### ISSUE TITLE
无法正确解析二进制序列

### ISSUE THREAD

**Issue by uamglx** [starwing/lua-protobuf#106]
我在遇见了一个令我十分苦恼地问题，用lua_protobuf 解析二进制序列，偶尔能够解析，偶尔有不能解析，不能解析序列其一如下
10 6F 1A 15 08 A0 3B 10 FC CC DE EE 05 1A 0A 73 75 62 6A 65 63 74 34 30 39 1A 16 08 A4 3B 10 FC CC DE EE 05 1A 0B 73 75 62 6A 65 63 74 36 35 32 39 1A 16 08 BF 3B 10 BD CD DE EE 05 1A 0B 73 75 62 6A 65 63 74 31 37 32 36 1A 16 08 C5 3B 10 BD CD DE EE 05 1A 0B 73 75 62 6A 65 63 74 34 30 39 38 1A 16 08 DC 3B 10 D4 D1 DE EE 05 1A 0B 73 75 62 6A 65 63 74 34 31 35 32 1A 16 08 DE 3B 10 D4 D1 DE EE 05 1A 0B 73 75 62 6A 65 63 74 31 30 38 31 22 04 01 00 00 00
奇怪的是有些情况下我能够解析，对于proto文件中的所有module我都解析成功过，但是有时又无法解析，假设保证二进制序列对应正确的模块，有什么可能会导致这样的事情发生？ 我是用c++获取远端的二进制字符串，使用dll回调回lua的，不知有没有影响（新手不太懂）

**Comment by starwing** [comment]
不能解析的时的报错是什么？

**Comment by starwing** [comment]
我这边反推你的数据结构解析成功了，你自己比较一下是不是有什么地方写错了，验证代码：

```Lua
local pb = require "pb"
local protoc = require "protoc"

protoc:load [[
syntax = "proto3";
message Data {
    message Inner {
        int32 f1 = 1;
        int64 f2 = 2;
        string f3 = 3;
    }
    int32 f1 = 2;
    repeated Inner f2 = 3;
    repeated fixed32 f3 = 4;
} ]]

local data = [[
10 6F 1A 15 08 A0 3B 10 FC CC DE EE 05 1A 0A 73 75 62 6A 65 63 74 34
30 39 1A 16 08 A4 3B 10 FC CC DE EE 05 1A 0B 73 75 62 6A 65 63 74 36
35 32 39 1A 16 08 BF 3B 10 BD CD DE EE 05 1A 0B 73 75 62 6A 65 63 74
31 37 32 36 1A 16 08 C5 3B 10 BD CD DE EE 05 1A 0B 73 75 62 6A 65 63
74 34 30 39 38 1A 16 08 DC 3B 10 D4 D1 DE EE 05 1A 0B 73 75 62 6A 65
63 74 34 31 35 32 1A 16 08 DE 3B 10 D4 D1 DE EE 05 1A 0B 73 75 62 6A
65 63 74 31 30 38 31 22 04 01 00 00 00
]]

local bin = data:gsub("%x%x%s*",
   function(s) return string.char(tonumber(s, 16)) end)

local t = pb.decode("Data", bin)
print(require "serpent".block(t))
```

输出结果：

```lua
{
  f1 = 111,
  f2 = {
    {
      f1 = 7584,
      f2 = 1574413948,
      f3 = "subject409"
    } --[[table: 0x7fa60e4218e0]],
    {
      f1 = 7588,
      f2 = 1574413948,
      f3 = "subject6529"
    } --[[table: 0x7fa60e421980]],
    {
      f1 = 7615,
      f2 = 1574414013,
      f3 = "subject1726"
    } --[[table: 0x7fa60e421a50]],
    {
      f1 = 7621,
      f2 = 1574414013,
      f3 = "subject4098"
    } --[[table: 0x7fa60e421b60]],
    {
      f1 = 7644,
      f2 = 1574414548,
      f3 = "subject4152"
    } --[[table: 0x7fa60e421c30]],
    {
      f1 = 7646,
      f2 = 1574414548,
      f3 = "subject1081"
    } --[[table: 0x7fa60e421b20]]
  } --[[table: 0x7fa60e41bf70]],
  f3 = {
    1
  } --[[table: 0x7fa60e41b000]]
} --[[table: 0x7fa60e41bf10]]

```

**Comment by uamglx** [comment]
你好，周末没有看GitHub不好意思，现在看了一下，使用你的测试用例无法解析，结果如下：
![image](https://user-images.githubusercontent.com/33451544/69505640-e79a8b00-0f65-11ea-810d-379549e528e3.png)
![image](https://user-images.githubusercontent.com/33451544/69505696-1d3f7400-0f66-11ea-8be9-2ea3b7ac1b66.png)

`package.path = "lua/?.luac;" .. package.path
package.path = "opt/?.lua;" .. package.path
package.path = "./?.lua;" .. package.path

if package.config:sub(1, 1) == "\\" then
    package.cpath = "opt/?.dll;" .. package.cpath
else
    package.cpath = "opt/?.so;" .. package.cpath
end
`这里是我的lua路径，我想把它放在一个文件夹里可以直接运行的那种（验证成功），
lua版本5.1.5 x64 自己编译的（需要使用x64，所以自己编的）
lua dll 编译后无法解析使用的是LuaBinaries下载的[lua-5.1.5_Win64_dll15_lib.zip](https://sourceforge.net/projects/luabinaries/files/5.1.5/Windows%20Libraries/Dynamic/)
不知道版本是否会有影响

最后结果如上图一样，仅输出123，没有卡死在了decode阶段，并且没有任何错误信息

**Comment by uamglx** [comment]
pb 是使用pb.c直接编译得到的，没有任何代码修改， 使用的是vs2017

**Comment by uamglx** [comment]
好的，谢谢，我再看看是否哪里出错了，主要是程序每次都卡在解析这里出错，让我产生了错觉 *……*
