### ISSUE TITLE
无法解析去描述文件

### ISSUE THREAD

**Issue by hanbim520** [starwing/lua-protobuf#108]
![image](https://user-images.githubusercontent.com/7490792/71437728-cfb55300-272d-11ea-85a6-d9fbc46fb70a.png)
![image](https://user-images.githubusercontent.com/7490792/71437732-d6dc6100-272d-11ea-9ce4-ef0a747bbc52.png)

**Comment by starwing** [comment]
这是二进制文件，直接用pb.load载入
