### ISSUE TITLE
首页readme里面的连接失效了

### ISSUE THREAD

**Issue by zhaozhantao** [starwing/lua-protobuf#114]
首页readme里，ToLua集成说明：这个地址http://changxianjie.com/tolua集成lua-protobuf/，点不开了，显示没有备案。可否维护一下呢？想在tolua里用呢。

**Comment by starwing** [comment]
这是第三方的文章……我也控制不了……如果有问题还是谷歌搜索一下吧……

**Comment by zhaozhantao** [comment]
好的
