### ISSUE TITLE
%1 is not a valid Win32 application.

### ISSUE THREAD

**Issue by CrownlessX** [starwing/lua-protobuf#116]
Hi
I'm using windows, and compiled dll. But when I got usage of it in file(local pb = require("pb"): 
lupa._lupa.LuaError: error loading module 'pb' from file '.\pb.dll':
        %1 is not a valid Win32 application.
and i can only run lua files with luac, not lua:

lua: error loading module 'pb' from file './pb.dll':
        Exec format error
stack traceback:
        [C]: in ?
        [C]: in function 'require'
        protobuf.lua:14: in main chunk
        [C]: in ?

**Comment by starwing** [comment]
It seems that the dll you compile and Lua executable doesn't match x86 and x64. Maybe you should check it twice.

**Comment by CrownlessX** [comment]
Checked and dll info tells that it compiled for x86. 
Will recompile and retest it later.
