### ISSUE TITLE
un-finished bytes (len 125 at offset 14)

### ISSUE THREAD

**Issue by lcp901219** [starwing/lua-protobuf#121]
我用lua-protobuf写一个wireshark的插件，在有些数据流的情况出现
Lua Error: C:\Program Files\Wireshark\limit_pb.lua:94: un-finished bytes (len 125 at offset 14)
code:
local limitMessage = assert(pb.decode("LimitPkt.LimitMessage", tvbuf(offset, pktlen-offset):string()))

**Comment by lcp901219** [comment]
syntax = "proto2";   //使用哪种协议 proto2
package LimitPkt;


message LimitReqMessage
{
    //limit 频控策略以组为单位
    optional string group = 1;
    //业务侧的业务id
    optional string appid = 2;   
    //业务侧的操作接口
    optional string interface = 3;   
    //频控的限额步长,值为0，使用limit模块配置中的步长
    optional int32 limit_step = 4;

    //请求带的唯一id,打印log用
    optional string client_reqid   = 5;
}


message LimitRspMessage
{
    optional int32 limit_errno = 1;
    //限额
    //0代表没有额度;
    //>0 代表额度数量
    //<0 代表额度为负,只有当步长>1的情况下才会为负
    optional int32 limit_value = 2;
}


message LimitMessage
{
    //seq号，状态机使用
    optional uint32 seq = 1;
    optional LimitReqMessage reqdata = 2;
    optional LimitRspMessage rspdata = 3;
}



data:
08 85 9c b8 29 12 7f 0a
0a 68 74 74 70 5f 63 6c 6f 75 64 12 1b 6b 6b 2d
63 6f 6d 69 63 2d 70 61 79 6d 65 6e 74 2d 31 32
35 33 35 34 33 39 39 32 1a 08 68 74 74 70 5f 67
65 74 20 00 2a 48 4d 54 55 34 4e 7a 41 77 4e 54
63 34 4e 6c 39 69 4e 47 51 33 4e 44 45 77 4f 56
38 34 4e 6a 55 31 4d 45 49 34 52 6b 5a 42 4f 54
4d 30 52 44 4e 45 4f 54 42 42 4d 6b 49 30 4f 54
41 33 51 6a 63 79 4e 44 45 31 4f 41 3d 3d

**Comment by starwing** [comment]
考虑下数据的确没有传完的可能性（tcp是流协议，没有包边界）

**Comment by lcp901219** [comment]
pb数据前有二进制的头，包括了整体数据长度，做了校验。pb包确认是完整的

**Comment by starwing** [comment]
我这边写了脚本，能解析成功你的二进制数据，结果如下：
```Lua
{
  reqdata = {
    appid = "kk-comic-payment-1253543992",
    client_reqid = "MTU4NzAwNTc4Nl9iNGQ3NDEwOV84NjU1MEI4RkZBOTM0RDNEOTBBMkI0OTA3QjcyNDE1OA==",
    group = "http_cloud",
    interface = "http_get",
    limit_step = 0
  } --[[table: 0x7fc6f0605b90]],
  seq = 86904325
} --[[table: 0x7fc6f0605b50]]
```

测试程序如下：
```Lua
local s = [[
08 85 9c b8 29 12 7f 0a
0a 68 74 74 70 5f 63 6c 6f 75 64 12 1b 6b 6b 2d
63 6f 6d 69 63 2d 70 61 79 6d 65 6e 74 2d 31 32
35 33 35 34 33 39 39 32 1a 08 68 74 74 70 5f 67
65 74 20 00 2a 48 4d 54 55 34 4e 7a 41 77 4e 54
63 34 4e 6c 39 69 4e 47 51 33 4e 44 45 77 4f 56
38 34 4e 6a 55 31 4d 45 49 34 52 6b 5a 42 4f 54
4d 30 52 44 4e 45 4f 54 42 42 4d 6b 49 30 4f 54
41 33 51 6a 63 79 4e 44 45 31 4f 41 3d 3d
]]

local pbio = require "pb.io"
s = s:gsub("%s*(%x%x)%s*", function(c)
   return string.char(tonumber(c, 16))
end)

pbio.dump("data", s)

local pb = require "pb"
local protoc = require "protoc"

assert(protoc:load [[
syntax = "proto2"; //使用哪种协议 proto2
package LimitPkt;

message LimitReqMessage
{
//limit 频控策略以组为单位
optional string group = 1;
//业务侧的业务id
optional string appid = 2;
//业务侧的操作接口
optional string interface = 3;
//频控的限额步长,值为0，使用limit模块配置中的步长
optional int32 limit_step = 4;

//请求带的唯一id,打印log用
optional string client_reqid   = 5;
}

message LimitRspMessage
{
optional int32 limit_errno = 1;
//限额
//0代表没有额度;
//>0 代表额度数量
//<0 代表额度为负,只有当步长>1的情况下才会为负
optional int32 limit_value = 2;
}

message LimitMessage
{
//seq号，状态机使用
optional uint32 seq = 1;
optional LimitReqMessage reqdata = 2;
optional LimitRspMessage rspdata = 3;
}
]])


local t = pb.decode("LimitPkt.LimitMessage", s)
print(require "serpent".block(t))
```

**Comment by lcp901219** [comment]
嗯。在wireshark中有的解析正常，有的解析失败，数据都没有问题。我再check下是不是wireshark哪里兼容有问题。感谢回复
