### ISSUE TITLE
proto文件中的枚举，需要手动在lua中重新定义吗

### ISSUE THREAD

**Issue by cuixingsong** [starwing/lua-protobuf#126]
由于不像protoc-gen-lua 会生成lua代码。如何在lua中使用proto文件中定义的枚举值？需要手动在lua中重新定义所有的enum类型？

**Comment by starwing** [comment]
不需要，用`pb.enum()`即可。

**Comment by yzyalfred** [comment]
用pb.enum()可以，但是用起来有点麻烦，没有直接生成一个lua table取值方便

**Comment by starwing** [comment]
可以用pb模块自己写一个生成表代码的脚本，并不难~
