### ISSUE TITLE
解析repeated int32类型时，遇到特定数据出现错误

### ISSUE THREAD

**Issue by songjunn** [starwing/lua-protobuf#128]
解析repeated int32类型时，如果数据中包含一个0，则会出现错误：un-finished bytes
如：
//proto
message UserInfo{
    repeated int32 value = 1;
}
//js代码
let userInfo = new UserInfo();
userInfo.addValue(1);
userInfo.addValue(0);
如上，收到前端构造的数据，解析会出现错误：un-finished bytes (len 2 at offset 3)
如不添加第二个value，或替换成非零值，userInfo.addValue(2)，就可以解析成功

**Comment by starwing** [comment]
你把binary传递给Lua的时候可能用错了函数，`lua_pushstring`会忽略0之后的所有内容，要使用`lua_pushlstring`来获取协议二进制字符串。

**Comment by songjunn** [comment]
受到您的启发找到问题所在了，虽不是lua_pushlstring的问题，不过确实和数据完整性有关，非常感谢
