### ISSUE TITLE
slua unreal 解析后每次数组值序列不同

### ISSUE THREAD

**Issue by jy00223715** [starwing/lua-protobuf#130]
第一次打印：Slua:     16  18  34  13  16  242 213 253 238 45  10  5   97  108 105 99  101 34  12  16  199 240 198 133 170 1   10  3   98  111 98  10  4   105 108 115 101
第二次打印：10  4   105 108 115 101 34  13  10  5   97  108 105 99  101 16  242 213 253 238 45  34  12  10  3   98  111 98  16  199 240 198 133 170 1   16  18

代码如下
`local pb = require "pb"
local protoc = require "protobuf/protoc"

--protoc = protoc.new()
--protoc:loadfile("C:/unrealGame/trunk/GameTrunk/Content/Lua/msg.proto")

assert(protoc:load [[
   message Phone {
      optional string name        = 1;
      optional int64  phonenumber = 2;
   }
   message Person {
      optional string name     = 1;
      optional int32  age      = 2;
      optional string address  = 3;
      repeated Phone  contacts = 4;
   } ]])

local TestNetwork = {}

function TestNetwork.Connect()
    local data = { account = "ilse", roleId  = 18}
    local data2 = {
        name = "ilse",
        age  = 18,
        contacts = {
            { name = "alice", phonenumber = 12312341234 },
            { name = "bob",   phonenumber = 45645674567 }
        }
    }
    local bytes2 = assert(pb.encode("Person", data2))
    print(string.byte(bytes2,1,string.len(bytes2)))
    print(bytes2)
end

function TestNetwork.SendMsg()
end

return TestNetwork`

**Comment by starwing** [comment]
不同是正确的……因为Lua都是没有顺序的哈希表……
