### ISSUE TITLE
取消默认值

### ISSUE THREAD

**Issue by liuwj414** [starwing/lua-protobuf#136]
现在lua-protobuf会给int，string类型付默认值，想取消这个功能，没有就直接为nil，要怎么修改呢？

**Comment by liuwj414** [comment]
自己回答一下，阅读了源码，把lpb_decode方法中的lpb_pushtypetable(L, LS, t)换成lua_newtable(L)就可以了.

**Comment by starwing** [comment]
pb.option "no_default_value"

**Comment by sundream** [comment]
这个库目前支持区分缺省值和默认值的接口?,比如has_field?

**Comment by starwing** [comment]
只要table里没有就是没有了（proto2），proto3无法区分，标准里也是没用默认值的。

**Comment by starwing** [comment]
另外，proto3支持一种可选的“optional”，具体看文档~
