### ISSUE TITLE
g++编译生成的lua在lua-protobuf中不支持

### ISSUE THREAD

**Issue by Txhua** [starwing/lua-protobuf#139]
g++编译生成的lua库运行lua-protobuf会报undefined symbol: lua_rawgetp错误

**Comment by starwing** [comment]
请保证pb.so和Lua的版本相同（g++找到的Lua头文件和lua可执行文件对应）

另外如果需要C++编译，将pb.c里的`#include <lua.h>`换成`#include <lua.hpp>`
