### ISSUE TITLE
could you release this code under an Open Source license?

### ISSUE THREAD

**Issue by seabadger** [starwing/lua-protobuf#14]
Hi,
I am very interested in using your lua-protobuf code for a project at work.
I also have a number of bugfixes that I'd like to contribute back to lua-protobuf 
(e.g., fixes for a few crashes, missing data type support, etc).

Unfortunately, I'm not allowed to to do this unless this project is explicitly licensed under an open source license.

Could you please release it under an Open Source license such as the BSD license, the MIT license, or the  Apache license?
  - https://opensource.org/licenses/MIT
  - https://opensource.org/licenses/BSD-2-Clause
  - https://opensource.org/licenses/Apache-2.0

(to do it, I think it's a matter of including a LICENSE file with the text of the license, and possibly some mentions of it in the README and the source files).

I really hope you can do this. Thanks in advance!

**Comment by starwing** [comment]
Okay I will add a License section in README.md

**Comment by seabadger** [comment]
Thanks very much! 
One note: you may want to have an explicit copyright notice, because apparently linking to the license may cause you to assign copyright to Lua.org (1994–2017 Lua.org, PUC-Rio).

**Comment by starwing** [comment]
I found that Github's License template is very easy to use :-) and I changed it to MIT license. Thank you :-)
