### ISSUE TITLE
有没有发现一个问题，pb.encode出来的bytes，每次都不一样？

### ISSUE THREAD

**Issue by xiaoniaojjj** [starwing/lua-protobuf#140]
有没有发现一个问题，pb.encode出来的bytes，每次都不一样？这是一个消息数据，每次encode出来的数据都不一样，但是长度是一样的
msg = {
        DeviceSN = '',
        IDFA = '',
        IMEI = 'f73930830383cdf152f35b3138eb79ad28e581cc',
        MacAddress = 'E0D55E687129',
        OAID = '',
        Umid = '',
        UnderAge = 0,
        accessToken = '',
        channelData = '52f74e8895ee2ec8',
        channelId = -1,
        channelId2 = 'Unity',
        channelName = 'Unity Editor',
        cityId = '',
        cityName = '',
        deviceId = '3',
        deviceName = 'android device',
        isYSDK = false,
        pf = '',
        pfKey = '',
        platformId = 'Unity',
        platformName = 'Unity Editor',
        provinceId = '',
        provinceName = '',
        sdkUserId = 'Unity',
        sessionId = '',
        strAccount = '637539246930858074',
        strGameId = '8471f4783bf83954',
        strGameKey = '1e373724970c4afc97b44d4c542ff1ad',
        strPlatform = 'android',
        strSign = '',
        token = '',
        verifyUrl = '',
        ysdkLoginType = 0
      }

**Comment by starwing** [comment]
因为Lua的表是没有顺序的，但是如果按照顺序解码，会导致性能问题（已经有人抱怨现在按照顺序赋值默认值的性能问题了……）

**Comment by fighterhit** [comment]
> 因为Lua的表是没有顺序的，但是如果按照顺序解码，会导致性能问题（已经有人抱怨现在按照顺序赋值默认值的性能问题了……） #147

想和其它语言序列化后的结果对比一下看有无问题，请问有选项支持按顺序吗？

**Comment by starwing** [comment]
> > 因为Lua的表是没有顺序的，但是如果按照顺序解码，会导致性能问题（已经有人抱怨现在按照顺序赋值默认值的性能问题了……） #147
> 
> 
> 
> @starwing 您好，想和其它语言（比如python的SerializeToString）序列化后的结果对比一下看有无问题，请问有选项支持按顺序吗？

有的，可以用encode_order这个option
