### ISSUE TITLE
lua怎么把二进制数据相连

### ISSUE THREAD

**Issue by SandWind** [starwing/lua-protobuf#142]

**Comment by starwing** [comment]
直接 `..` 嘛

**Comment by SandWind** [comment]
遇到一个问题当protobuf解码字段为bytes用字符连接符 操作后连接出来的内容再protobuf解码就会出现掉数据现象

**Comment by starwing** [comment]
对proto3，非repeated的数据可能会被后面的数据冲掉。给一个最小可运行的例子说明一下掉数据吧，如果真的有我就修一下。

**Comment by SandWind** [comment]
我发现 用table.concat就没问题

**Comment by rainingmaster** [comment]
`table.concat` 和 `..` 的作用应该是一致的。这是 lua 的语法问题了，感觉和这个库没有什么关系哈。
