### ISSUE TITLE
Subfields in query string are not mapped into protobuf

### ISSUE THREAD

**Issue by git-torrent** [starwing/lua-protobuf#144]
I have situation from specification:
https://github.com/googleapis/googleapis/blob/master/google/api/http.proto#L113

Message:
```
message GetMessageRequest {
  message SubMessage {
    string subfield = 1;
  }
  string message_id = 1; // Mapped to URL path.
  int64 revision = 2;    // Mapped to URL query parameter `revision`.
  SubMessage sub = 3;    // Mapped to URL query parameter `sub.subfield`.
}
```

Request:

`GET /v1/messages/123456?revision=2&sub.subfield=foo`

However, all the structured fields arrive empty, only primitive fields are filled.
The resulting proto has values

```
  message_id: 123456,
  revision: 2,
  sub.subfield = ""
```

and should be

```
  message_id: 123456,
  revision: 2,
  sub.subfield = "foo"
```

**Comment by starwing** [comment]
Could you give me a binary data (hexadecimal decoded) causing the wrong result?  I could look into to see why it doesn't get decoded.

**Comment by git-torrent** [comment]
I am using grpc-gateway for kong and it happens at this point:

https://github.com/Kong/kong-plugin-grpc-gateway/blob/master/kong/plugins/grpc-gateway/deco.lua#L251

namely:
```
pb.encode("GetMessageRequest", { ["sub.subfield"] = foo,})
```
here are dumps:

```
InputType: GetMessageRequest, client: 127.0.0.1, server: kong, request: "GET /v1:GetMessage?sub.subfield=foo HTTP/1.1"
Payload: { ["sub.subfield"] = foo,} , client: 127.0.0.1, server: kong, ...
Body:
0000: 00 00 00 00 00 ....., 

client: 127.0.0.1, server: kong, ...

```

are arguments of pb.encode correct?

**Comment by starwing** [comment]
maybe you should use { sub = { subfield = foo } }？

**Comment by git-torrent** [comment]
Yes, thank you. This is clearly bug of Kong plugin.

**Comment by git-torrent** [comment]
Not a bug
