### ISSUE TITLE
使用instrument 发现有一个内存泄露

### ISSUE THREAD

**Issue by alexliuf5** [starwing/lua-protobuf#156]
pbL_grow 方法 ，提示函数对应的是1377行：
nh = nsize < size ? NULL :
            (pb_ArrayHeader*)realloc(h, sizeof(pb_ArrayHeader)+nsize*objs);

**Comment by alexliuf5** [comment]
<img width="437" alt="Screen Shot 2021-08-23 at 5 07 23 PM" src="https://user-images.githubusercontent.com/66632259/130519820-44bb9036-7f91-4eab-b9e2-acd2595c1627.png">

**Comment by alexliuf5** [comment]
<img width="566" alt="Screen Shot 2021-08-23 at 5 10 28 PM" src="https://user-images.githubusercontent.com/66632259/130520187-7aaad7a7-81af-4bfb-a221-94d83878d3af.png">

**Comment by starwing** [comment]
嗯，oneof的确没释放，已经修复了～多谢！

**Comment by alexliuf5** [comment]
干得漂亮😹 。。。神速
