### ISSUE TITLE
Why does `decode` keeps every field even without value in message

### ISSUE THREAD

**Issue by yuhongyu879** [starwing/lua-protobuf#157]
`decode` will drop field for refrerence type which value is empty in a message, that's good but when the type is `repeated` or `map`, `decode` will generate a empty table which will let cjson encode it to `{}` (or `[]` when use [empty_array_mt](https://github.com/openresty/lua-cjson#empty_array_mt)),that may cause type error in upstream service. can `decode` drop field when the types above(repeated/map) is empty?

**Comment by starwing** [comment]
It seems that protobuf3 need the empty table, if you use protobuf2, the repeated table should not exists. But you can use `pb.hook()` interrface to remove that table just after decodeed.

**Comment by yuhongyu879** [comment]
how pb.hook work with `repeated` type (i have hundreds types defined in proto), actually i want treat empty `repeated`/`map` defferently(for json encode). and can u explain more clearly about it please？

> It seems that protobuf3 need the empty tab

**Comment by yuhongyu879** [comment]
solved by removing all empty tables from decoded obj

**Comment by yuhongyu879** [comment]
solved by removing all empty tables from decoded obj

**Comment by starwing** [comment]
Sorry for late reply, you could look this line in source: 
https://github.com/starwing/lua-protobuf/blob/3f2d706aca7b57c3ffc27daf85c03c7d21a21f7c/pb.c#L1320

just remove it/change it with your own flags will remove the empty table.

the `pb.hook()` interface acts on a message tyue, but "map" itself is not a message type, so `pb.hook "map"` is not work :-(

currently I have no way to config `pb` not produce the empty table other than modifying the source code, sorry for that...
