### ISSUE TITLE
反序列化来自C#的二进制流的时候，出现错误

### ISSUE THREAD

**Issue by Jayatubi** [starwing/lua-protobuf#16]
通过C#序列化一个带有`repeated int32`字段的proto结构体到二进制流，在通过lua-protobuf反序列化将会出现错误：

```
type mismatch at offset 2, varint expected for type int32, got bytes
```

proto文件定义：

```protobuf
syntax="proto3";

message MyMessage
{
    repeated int32 intList = 1;
}
```

C#代码：

```csharp
using System.IO;

public class Application
{
    public static int Main(string[] args)
    {
        var instance = Google.Protobuf.JsonParser.Default.Parse<MyMessage>(File.ReadAllText("data.json"));
        using (var ms = new MemoryStream())
        using (var cs = new Google.Protobuf.CodedOutputStream(ms))
        {
            instance.WriteTo(cs);
            cs.Flush();
            File.WriteAllBytes("pb.bin", ms.ToArray());
        }

        return 0;
    }
}
```

data.json

```json
{
    "intList": [
        1,
        2,
        3
    ]    
}
```

C#生成的二进制流：

```
  Offset: 00 01 02 03 04 05 06 07 08 09 0A 0B 0C 0D 0E 0F 	
00000000: 0A 03 01 02 03                                     .....
```

Lua代码：

```lua
local pb = require("pb")
local json = require("rapidjson")

if pb.loadfile("../proto/pb.description") then
    local file = io.open("../csharp/pb.bin", "rb")
    local bytes = file:read("*a")
    file:close()
    local obj, message = pb.decode("MyMessage", bytes)
    if obj ~= nil then
        print(json.encode(obj))
    else
        print(message)
    end
else
    print("pb description load failed")
end
```

**Comment by Jayatubi** [comment]
大概知道原因了。Proto3里面的`repeated`默认是`[packed=true]`，但是lua-protobuf没有做这个处理。手动在proto里面加上[packed=true]可以破。

**Comment by starwing** [comment]
fix it by HEAD

**Comment by JackZheng1989** [comment]
> 大概知道原因了。Proto3里面的`repeated`默认是`[packed=true]`，但是lua-protobuf没有做这个处理。手动在proto里面加上`[packed=true]`可以破。
> 
> 官方描述摘录：https://developers.google.com/protocol-buffers/docs/encoding
> 
> > Version 2.1.0 introduced packed repeated fields, which in proto2 are declared like repeated fields but with the special [packed=true] option. `In proto3, repeated fields are packed by default.` These function like repeated fields, but are encoded differently. A packed repeated field containing zero elements does not appear in the encoded message. Otherwise, all of the elements of the field are packed into a single key-value pair with wire type 2 (length-delimited). Each element is encoded the same way it would be normally, except without a tag preceding it.

尝试在proto中添加`[packed=true]`，又出现了新的问题：
![image](https://user-images.githubusercontent.com/40486759/117826499-c71dd800-b2a2-11eb-98b7-32a29ed6f576.png)

**Comment by starwing** [comment]
@JackZheng1989 检查你的lua-protobuf版本，尽量用最新的，最新的已经不需要packed了

**Comment by TongZiGang** [comment]
@starwing 作者大大有头绪么？这个我应该怎么做？

**Comment by starwing** [comment]
@TongZiGang 如果Windows的正常，那Android的肯定也正常，除非版本不一样。因为代码都是跨平台的。建议还是检察一下pb.c/pb.h和protoc.lua这三个文件和HEAD的diff。
