### ISSUE TITLE
Would you like to release a new version?

### ISSUE THREAD

**Issue by spacewander** [starwing/lua-protobuf#184]
I am going to switch our lua-protobuf fork to the latest release. However, the latest version is released several months ago (https://github.com/starwing/lua-protobuf/commit/9a55710d40ce0ede16fbf5f4fea6eb937537f55b) and contains a memory leak https://github.com/starwing/lua-protobuf/commit/3f2d706aca7b57c3ffc27daf85c03c7d21a21f7c.

It would be great if you could release a new version to luarocks. Thank you!

**Comment by starwing** [comment]
new release landed.
