### ISSUE TITLE
根据函数名来推测,这两个宏是不是写反了

### ISSUE THREAD

**Issue by chamzzzzzz** [starwing/lua-protobuf#19]
https://github.com/starwing/lua-protobuf/blob/acfaeddf6c3bdd89d1f5e69e88d415f589bb8d35/pb.h#L619

https://github.com/starwing/lua-protobuf/blob/acfaeddf6c3bdd89d1f5e69e88d415f589bb8d35/pb.h#L605

**Comment by starwing** [comment]
干得好……因为这俩函数pb.c并没用到所以没有测试出来……多谢多谢~
