### ISSUE TITLE
Proto3

### ISSUE THREAD

**Issue by matiasinsaurralde** [starwing/lua-protobuf#2]
Hi, does this project work with proto3?

**Comment by starwing** [comment]
I'm much time for this project. I will look into proto3 when have time. It's great if you have some information about changes from proto2 :)

**Comment by matiasinsaurralde** [comment]
Yes, I'll research about it, will try to contribute if I find time.
Thanks for the reply!

**Comment by starwing** [comment]
And, because lua-protobuf just read *.pb file for schema. It should support proto3's pb file. (when I write lua-protobuf, it's time that proto3 is in beta-stage. And I use proto3's Descriptor file for reference. So you can try first. It must likely work with proto3 out of box.

**Comment by vkill** [comment]
+1

**Comment by despiegk** [comment]
+1

**Comment by starwing** [comment]
the new implement of lua-protobuf (in new branch) support proto3 correctly, but I need time to test and release this branch, maybe when the chinese spring holiday.

**Comment by woodzong** [comment]
I can't wait for it(support proto3). awesome!

**Comment by starwing** [comment]
Now proto3 are fully supported by the new version!
