### ISSUE TITLE
protoc.lua: compilefile fails with "bad argument #2 to '?' (string expected at field 'default_value', got number)"

### ISSUE THREAD

**Issue by seabadger** [starwing/lua-protobuf#20]
Tried using protoc module to load a .proto file, failed with the error mesage:
'''bad argument #2 to '?' (string expected at field 'default_value', got number)'''

Code snippet:
'''
local protoc = require "protoc"
local pb = require "pb"
local p = protoc.new()
-- set up paths as appropriate
-- p.paths[#p.paths+1] = "foo"
-- p.paths[#p.paths+1] = "bar"
local descriptor = p:compilefile( "relative/path/to/some.proto" )
'''

**Comment by starwing** [comment]
It's because google's Descriptor message only accept string as default_value, but protoc compiler returns lua types such as integer or number, ets. Fixed on HEAD. Thanks for feedback.

**Comment by starwing** [comment]
@seabadger hello! Is this fixed?

**Comment by starwing** [comment]
close for no feedback

**Comment by seabadger** [comment]
Hi. Sorry, I try to respond quickly when I can, but it doesn't always work out.
Not sure if this one is fixed or not, as the method was not even accessible; I filed #36 for that.

Also, thanks for all the fixes -- all the tests I have so far seem to be passing.
I'll try to figure out a way to contribute them, will let you know when it's ready (might take some time).
