### ISSUE TITLE
enum中option allow_alias = true;的支持失效

### ISSUE THREAD

**Issue by dingdalong** [starwing/lua-protobuf#213]
`test.lua`中的示例可以通过，但是将`enum`放到最外层时，`option allow_alias = true;`失效
例如：
```
enum test_alias {
    option allow_alias = true;
    enum1 = 1;
    enum2 = 2;
    enum3 = 2;
}
```
应该是提交[`fix options support`](https://github.com/starwing/lua-protobuf/commit/9067ffd7adbf8e4fd4a3e7d2de276eaaa62399ce)导致了该问题。

**Comment by starwing** [comment]
fixed now.
