### ISSUE TITLE
Incorrect decode error

### ISSUE THREAD

**Issue by surfskidude** [starwing/lua-protobuf#225]
I believe I got an incorrect decode error. I got the following error:
type mismatch for field 'timestamp' at offset 2, varint expected for type uint64, got bytes
However, I uploaded the data to this protobuf decoder https://protogen.marcgravell.com/decode and the data does not include 'bytes'

I have attached the data and a test script.
[failed.zip](https://github.com/starwing/lua-protobuf/files/10068913/failed.zip)

**Comment by starwing** [comment]
to parse your data to raw wire format it results:
```
0A (1: bytes 06) (length: 6)
	76 31 2E 30 2E 30
12 (2: bytes 1A) (length: 26)
	0A (1: bytes) 16 (length: 22)
		44 65 76 69 63 65 20 43 6F 6E 74 72 6F 6C 2F 52 65 62 69 72 74 68
	70 (14: varint) 01
28 (5: varint) 01
```

So it seems like a `Template` type, not `Payload` type

**Comment by surfskidude** [comment]
Yes, you are correct. Sorry for the noise.
