### ISSUE TITLE
pb.option "enum_as_value" - value is always zero

### ISSUE THREAD

**Issue by alonbg** [starwing/lua-protobuf#230]
runtime: luajit-openresty/bin/luajit release LuaJIT 2.1.0-beta3

[commit 762b027 test.lua:L367](https://github.com/starwing/lua-protobuf/blob/2a2b0b95117642ad9470bfe0add7dd6ce82f3869/test.lua#L367)  latest as of this writing

```lua
pb.option "enum_as_value" 
```
test will fails for enum values mapped to  numbers other than 0.
but it passes  as [only]  0 is being asserted :)

**Comment by starwing** [comment]
this is cause by the test itself. It just test `pb.defaults` which gets the default value of all field. and the default value of `color` is 0. It's not the test for `pb.decode`

**Comment by alonbg** [comment]
makes sense.  thanks @starwing
