### ISSUE TITLE
unknown hook works only when attached to module

### ISSUE THREAD

**Issue by alonbg** [starwing/lua-protobuf#231]
Problem: loading this [envoy](https://github.com/envoyproxy/envoy/blob/81fa353d7d9f54ca4f47846f06183755d3b74f1a/api/envoy/extensions/filters/http/ext_proc/v3/ext_proc.proto#L98) proto

With the following environment & prerequisites:
LuaJIT 2.1.0-beta3 -- Copyright (C) 2005-2022 Mike Pall. https://luajit.org/
lua-protobuf -[ latest commit as of this writing  ](https://github.com/starwing/lua-protobuf/commit/2a2b0b95117642ad9470bfe0add7dd6ce82f3869)

``` lua
PROTO_PREFIX =  "/etc/proto/"

local protoc_import_paths = {
    ".",
    PROTO_PREFIX .. "envoy/api", -- https://github.com/envoyproxy/envoy
    PROTO_PREFIX .. "xds", -- https://github.com/cncf/xds.git
    PROTO_PREFIX .. "protoc-gen-validate",  -- https://github.com/bufbuild/protoc-gen-validate
    "/usr/local/include" -- https://github.com/google/protobuf
}


```
fails on 

``` log
`envoy/config/core/v3/base.proto:98:3: unknown type 'type.v3.SemanticVersion'` 
`envoy/config/core/v3/base.proto:273:3: unknown type 'type.v3.Percent'`
`envoy/config/core/v3/base.proto:496:3: unknown type 'type.v3.FractionalPercent'`
`/etc/proto/envoy/api/envoy/service/ext_proc/v3/external_processor.proto:183:3: unknown type 'config.core.v3.HeaderMap'`
`/etc/proto/envoy/api/envoy/service/ext_proc/v3/external_processor.proto:288:3: unknown type 'type.v3.HttpStatus'`
```

I realized that this is solved by prefixing these types with ` .envoy.`
Thus I created this hook

```lua
local unknown_type = function(self, name)    
        if name == "type.v3.SemanticVersion"
           or name == "type.v3.Percent"
           or name == "type.v3.FractionalPercent"
           or name == "config.core.v3.HeaderMap"
           or "type.v3.HttpStatus" then
            return ".envoy." .. name, "message"
        end
    end

proto_inst.unknown_type = unknown_type
```

However, it still errored. It workes only when hook is attached to the module itself (i.e. `protoc` )

```lua
local protoc = require("protoc")
protoc.unknown_type = unknown_type
```

Any ideas ?

**Comment by starwing** [comment]
I have made a new commit for better unknown handling in `proton.Lua`, please try it out to see whether it solve your issue.

**Comment by starwing** [comment]
okay, thanks for the catch! Now the tests are passed.
