### ISSUE TITLE
pb.encode的时候，如果table的metatable有定义__pairs，则通过__pairs进行遍历

### ISSUE THREAD

**Issue by Jayatubi** [starwing/lua-protobuf#25]
pb.encode的时候，如果table的metatable有定义__pairs，则通过__pairs进行遍历

**Comment by diegonc** [comment]
Sorry, I don't understand this issue. Has it anything to do with the field order at encode time? I'm using two libraries (java and this one) to create the same protobuf and getting different ordering.

https://developers.google.com/protocol-buffers/docs/encoding#order

**Comment by starwing** [comment]
@diegonc Hi, protobuf's spec do not define the order of encoded bytes. So it's valid to just have random order. if you really need specific order, you could write message yourself using `pb.buffer` low level routines.

**Comment by diegonc** [comment]
Yeah, it's valid for parser but encoders should sort them by number according to the link posted above.

Anyway, I'm trying in the gist below to use `pb.buffer` but I'm no sure how to send fields and following Lpb_encode is getting hard as it uses things that don't seem to be available in Lua. Can you help me fill the gaps? Thanks

https://gist.github.com/diegonc/d6af5520e8966340ccf27977220beb71
