### ISSUE TITLE
Proto - JSON transcoder

### ISSUE THREAD

**Issue by git-torrent** [starwing/lua-protobuf#255]
Hello, on Kong we have long open [PR that adds the functionality of proto - json transcoder](https://github.com/Kong/kong/pull/8297). I was advised it might save some time if that transcoder would be part of lua-protobuf package. 

Is there any possibility to add it to this project? What are requirements? The functionality is concentrated into one file https://github.com/Kong/kong/pull/8297/files#diff-3a78d93fbe0ba99669d5d760d6f3cf5c536dd93deab5b499f8528d3c0eaacf29 (to simulate google's solutions - [go](https://pkg.go.dev/google.golang.org/protobuf/encoding/protojson), [c++](https://protobuf.dev/reference/cpp/api-docs/google.protobuf.util.json_util/) or [C#](https://protobuf.dev/reference/csharp/api-docs/class/google/protobuf/json-formatter)).

I am not a C coder, maybe a Lua one, so my contributions are limited. The code is working and tested. It might be slower than your standard and definitely can benefit from some features of pb.c. Of course, I cannot expect anyone to add these features for me. 

Thank you for answer

All the best.

**Comment by starwing** [comment]
You could add jsonproto.lua to lua-protons repo here, but there some issues. That module depends on date and cjson module which is not used by lua-protobuf. So maybe it's better to leave it as a standalone module that depends on lua-proyobuf?
