### ISSUE TITLE
Name resolution is failing

### ISSUE THREAD

**Issue by git-torrent** [starwing/lua-protobuf#268]
I have three files (in attachment) 
[proto.zip](https://github.com/starwing/lua-protobuf/files/15149887/proto.zip)

The example is for Windows (my workstation), but the same happens on Linux. Running the test.lua causes error:

`Exception has occurred: ../Program Files (x86)/Lua/5.1/lua/protoc.lua:82: c:\proto\a\x.proto:13:3: unknown type 'b.Z`

The same with `protoc --cpp_out=. -I c:\proto c:\proto\a\x.proto` does everything without any complaint.

According to https://protobuf.dev/programming-guides/proto3/#name-resolution the names should be resolved inside out. This seem to fail in protoc-lua. If I change the attribute to use definition fully qualified name, it works.

```
message X {
  Y y = 1; // local import
  something.else.b.Z z = 2; // import from other package
}
```

We do not use fully qualified names because of zero added value (visual noise) if the common part is enough for google tooling.

In lua protoc, is this a bug or a feature? Can it be fixed to behave according to spec?

Thank you

**Comment by starwing** [comment]
You should load all dependencies of current proto file, or using `include_imports` flag when compiling proto files.

**Comment by starwing** [comment]
Have you tried the latest lua-protobuf? it works for me:
```
local protoc = require "protoc" -- protocol buffer compiler, similar to `pb` standing for `protocol buffers`

local p = protoc.new();

-- p.include_imports = true;
p:addpath( "" );
p:loadfile( "a/x.proto" );

print ( "loaded" );
```

produces:
```
$ lua  -- test.lua
loaded
```

**Comment by git-torrent** [comment]
Thank you, lua-protobuf-0.5.1-1 works perfectly
