### ISSUE TITLE
inconsistent proto3 enum handling (some fields decoded as names, other as values)

### ISSUE THREAD

**Issue by seabadger** [starwing/lua-protobuf#27]
Given the following proto3 syntax type:
```protobuf
message Foo {
  enum Color {
    RED = 0; // 0 must be present, is the default, and must be first in list
    GREEN = 1;
    BLUE = 2;
  }
  repeated Color color_enumf = 1;
```
and the following input:
```lua
 {
   color_enumf = { 2, "RED", 34, "z" }
}
```

After encoding and decoding, the output looks as follows:
```lua
{
  color_enumf = { "BLUE", 0, 34 }
}
```
The inconsistency  is that an input of 2 (or "BLUE") appears as in the output as "BLUE" (this is good), but input of 0 (or "RED") appears in output as 0. So -- some fields get translated to the enum names, others to enum values.

(to be clear, the other two inputs behave as I expect: 34 stays 34, "z" is ignored; both of these are reasonable).

**Comment by seabadger** [comment]
setting "enum_as_name" explicitly does not change anything.

setting "enum_as_value" makes things consistently use values.

**Comment by starwing** [comment]
this because the current HashTable implement do not support encode `0`...

I will try to solve this...

**Comment by starwing** [comment]
fix at HEAD.
