### ISSUE TITLE
lua接收到带有optional的proto3协议解析后出现了 _字段名 = "字段名"

### ISSUE THREAD

**Issue by Wang-nine** [starwing/lua-protobuf#274]
lua接收到经过java序列化后的带有optional的proto3协议解析后出现了 _字段名 = "字段名"，例如 _paramName1 = "paramName1" _paramName2 = "paramName2"，请问下这个是经过了什么特殊的处理吗，谢谢

**Comment by starwing** [comment]
proto3的optional实际上是单元素的oneof的语法糖，luapb解析后无法区别是optional还是oneof，你看到的这个域是oneof留下的，告诉你被设置的是哪个成员（你可以当做has_field来用）
