### ISSUE TITLE
proto3 aliased enum not working

### ISSUE THREAD

**Issue by seabadger** [starwing/lua-protobuf#28]
Given the following proto3 syntax type:
```protobuf
message Foo {
  enum AliasedEnum {
    option allow_alias = true;
    ZERO = 0;
    ONE = 1;
    TWO = 2;
    FIRST = 1;
  }
  repeated AliasedEnum aliased_enumf = 2;
}
```
and the following input:
```lua
 {
  aliased_enumf = { "ZERO", "FIRST", "TWO", 23, "ONE" }
}
```

encoding and then decoding produces the following:
```lua
{
  aliased_enumf = { 0, "TWO", 23, "ONE" }
}
```

Basically, the entry 'FIRST' is ignored, but should not be.
(note: aliased enums are ambiguous, so it's ok to make a choice to decode a value as either of the names; but ignoring it is clearly a bug).

**Comment by seabadger** [comment]
PS as you may have guessed, I have a test suite I'm running this library against. 
I will be filing more bugs in the near future.
If you are interested, I can share the test suite -- one issue is that it depends on googletest, not sure if that's a problem).

**Comment by starwing** [comment]
Fixed

**Comment by starwing** [comment]
@seabadger hi, if you will, you can transfer they to test.lua and make a pull request. Or you could just share and I do the transform
