### ISSUE TITLE
proto3 'Any' type not working 

### ISSUE THREAD

**Issue by seabadger** [starwing/lua-protobuf#29]
This used to work in the previous implementation (prior to recent changes).
Not sure if the problem is a bug, or if the usage pattern changed, reporting what I encountered.

Given the following proto3 type:
```protobuf
syntax = "proto3";
package foo;
import "google/protobuf/any.proto";

message Bar {
  string   stringf   = 1;
}


message Foo
{
  google.protobuf.Any any = 1;
}
```

And the following input usage:
```lua
local ANY_TYPE = "foo.Bar"
local ANY_TYPE_URL = "type.googleapis.com/foo.Bar"

local prim  = {
   stringf = "this is a string in the any message",
}

local encoded_bar, msg = pb.encode( ANY_TYPE, prim )
local obj = {
   any = {
      type_url = ANY_TYPE_URL,
      value = encoded_bar
   }
}
```

Encoding and decoding  "obj" above produces an empty table.

As I mentioned, the same exact usage pattern worked fine in the previous version of the code
(I'd had to fix the handling of 'bytes' for that, but after that it worked fine).

**Comment by starwing** [comment]
have you load the "any" proto file? you can not just import it, import only use to confirm that "Any" is just a type, but not load the any.proto into `pb`.

maybe you should protoc:loadfile "google/protobuf/any.proto" before load your schema

**Comment by seabadger** [comment]
Thanks -- you're right, I had assumed that imports are automaticlaly handled and don't need to be explicitly loaded. Requesting that as a feature in #30, closing this one.
