### ISSUE TITLE
proto3: imported types not working?

### ISSUE THREAD

**Issue by seabadger** [starwing/lua-protobuf#30]
Given the following type definitions:
File imported.proto:
```protobuf
syntax = "proto3";
package foo;

message SimpleImported {
  bool     flag     = 13;
  string   stringf   = 14;
}
```
File simple.proto:
```protobuf
syntax = "proto3";
package foo;

import "imported.proto";

message Foo
{
  foo.SimpleImported imported_simple_proto3 = 8;
}
```

and the following input:
```lua
 {
   imported_simple_proto3 = {
      stringf = "a string",
      flag = true,
   }
}
```

Encoding and decoding results in an empty table.

The same issue occurs if 'simple.proto' contains a proto2 type

It's possible that the 'Any' issue I just reported is caused by broken imports as well, not sure.

**Comment by starwing** [comment]
It's the same issue in #29. Even in google's protoc, if you do this:
`protoc -o out.pb out.proto`
and import bar.proto in out.proto, the output "out.pb" only contains messages of out.proto, not out.proto and bar.proto. you need compile bar.proto again and load it manually.

**Comment by seabadger** [comment]
That's true; however, I think this significanly reduces the usefulness of this feature (i.e., if calling code has to know all the imports).
google's protoc supports the  --include_imports switch, which causes it to actually traverse the imports and load them (assuming they're in the search path). Would you mind implementing this? (it could be an optionally enabled behavior, if the current behavior is generally preferred).
Implementing it should be pretty straightforward, as FileDescriptorProto  exposes the imports via the 'dependency' field (and you'd keep track of files already loaded)

**Comment by seabadger** [comment]
changed subject accordingly

**Comment by starwing** [comment]
Sorry for the late reply, we are just in the Chinese Spring Festival (the Chinese New Year), and I got a cold :-(

I will implement this enhancement in next push, thanks

**Comment by starwing** [comment]
Fixed
