### ISSUE TITLE
protoc.lua incorrectly refuses to parse proto2 map fields w/o optional/required/repeated label.

### ISSUE THREAD

**Issue by seabadger** [starwing/lua-protobuf#32]
Given a proto2 type definition with the following field:
```protobuf
  map<string, string> map_strstr = 6;
```
protoc.lua refuses to parse the type, producing the following message:
  **proto2 disallow missing label**

However, according to the spec, **Maps cannot be repeated, optional, or required.**
(see https://developers.google.com/protocol-buffers/docs/proto#maps )

**Comment by seabadger** [comment]
just to be clear: google's protoc refuses to compile a file that protoc.lua accepts. protoc.lua refuses to compile a file that google's protoc accepts. This is not a minor problem -- maps are currently unusable in proto2.

**Comment by starwing** [comment]
Fixed
