### ISSUE TITLE
LuaJIT support?

### ISSUE THREAD

**Issue by rucuriousyet** [starwing/lua-protobuf#33]
Is LuaJIT support at all possible? I am trying to use this library for the net communication in a Love2D-based game.

**Comment by starwing** [comment]
yes, it has luajit test in Travis

**Comment by rucuriousyet** [comment]
When trying to run the example provided on Linux using LuaJIT 2.0.5 

```
luajit: error loading module 'pb' from file './pb.so':
	./pb.so: undefined symbol: luaL_setfuncs
stack traceback:
	[C]: at 0x00452b30
	[C]: in function 'require'
	example.lua:1: in main chunk
	[C]: at 0x00404680
```

**Comment by rucuriousyet** [comment]
How? I used pkg-config to get the flags for lua51 and also luajit-2.0...
neither worked.

**Comment by rucuriousyet** [comment]
Nevermind... figured it out. Might be nice to add some documentation around this for future users. Thanks anyways..
