### ISSUE TITLE
protoc:load有BUG

### ISSUE THREAD

**Issue by yiyucyp** [starwing/lua-protobuf#35]
如果加载下面文本，就会出错

出错时的调用栈
LuaException: protoc.lua:10: attempt to index a function value (local 't')
stack traceback:
	protoc.lua:10: in upvalue 'default'
	protoc.lua:695: in local 'body_parser'
	protoc.lua:713: in local 'top_parser'
	protoc.lua:756: in function 'protoc.parse'
	protoc.lua:992: in function 'protoc.compile'
	protoc.lua:1004: in function 'protoc.load'
	protobuf3.lua:53: in main chunk
	[C]: in function 'require'
	ProtobufTest.lua:2: in main chunk
	[C]: in function 'require'

syntax = "proto3";
package protocol;
//import "pb_common.proto";
//import "pb_login.proto";

message get_ping {
}

message get_ping_ret {
}

enum register_result {
    enumZero = 0;
	registerSuccess = 1;		    //注册成功
	userExists = 2;				    //用户名已经存在
	invalidFormat = 3;				//用户名格式不符合规范
	invalidServer = 6;              //连接游戏服务器失败
}

//登录服务器注册账号
message login_register{
    string username = 1;	    //用户名
	string password = 2;		//密码
}

//登录服务器注册账号返回
message login_register_ret {
    register_result result = 1;    //注册结果
    int32 uid = 2;                 //用户id 注册成功返回此字段
    string token = 3;              //登录令牌 注册成功返回此字段
    string gameServer = 4;         //返回游戏服务器地址
    string msg = 5;                //反馈消息 登录失败返回
}

message C2S {
    int32 seq = 1;     //消息序号

    //-----------------通用接口---------------
    get_ping get_ping = 3;

    //-----------------登录模块接口---------------
    login_register login_register = 6;
}

message S2C {
    int32 seq = 1;
    //-----------------通用接口---------------
    get_ping_ret get_ping_ret = 3;

    //-----------------登录服接口---------------
    login_register_ret login_register_ret = 6;
}

//rpc 服务间转发
service RPCService {
    rpc request(C2S) returns(S2C);
}

**Comment by starwing** [comment]
的确，解析service会出问题，多谢反馈，已经在HEAD提交了修复~
