### ISSUE TITLE
Random file created after usage

### ISSUE THREAD

**Issue by rucuriousyet** [starwing/lua-protobuf#37]
Im trying to figure out why the following code produces a directory and file: `lua-protobuf/pb.gcda`

```lua
local socket = require "socket"
local schema = require "utils.net.schema"

package.cpath = "./src/lib/?.so"
local pb = require "pb"
local protoc = require "lib.protoc"

pb.load(assert(protoc.new():compile(schema)))
local sock = socket.udp()

sock:settimeout(nil)
sock:setpeername("%s", %i)

while true do
	local sendMsg = love.thread.getChannel('net.queue.outgoing'):demand() -- blocks until receive
        if sendMsg then
		sock:send(assert(pb.encode("schema.Packet", {
			TypeOf = sendMsg.typeof,
		        Body = assert(pb.encode(sendMsg.typeof, sendMsg.body)),
		})))
	end
end
```

this also seems to happen with the compilation method shown in the example.

**Comment by seabadger** [comment]
According to 
  https://gcc.gnu.org/onlinedocs/gcc/Gcov-Data-Files.html

> The .gcda count data file is generated when a program containing object files built with the GCC -fprofile-arcs option is executed. A separate .gcda file is created for each object file compiled with this option. It contains arc transition counts, value profile counts, and some summary information.

**Comment by rucuriousyet** [comment]
Any way to disable this behavior?

-sent from my OnePlus X

**Comment by rucuriousyet** [comment]
I don't recall using any such flag to compile the pb.so file. I don't think
this is something called for in the rockspec file but I will check.

**Comment by rucuriousyet** [comment]
```
luarocks make lua-protobuf/rockspecs/lua-protobuf-scm-1.rockspec
CFLAGS="-fPIC -Wall -Wextra --coverage" LIBFLAGS="-shared --coverage"
```

**Comment by starwing** [comment]
so maybe you should remove --coverage flag, I need it for travis-ci

**Comment by rucuriousyet** [comment]
That works, thanks for the tip. Just for future developers, would you be open to documenting the build process a bit? Something like the following may help alot (building on Linux):

```shell
pip install hererocks
git clone https://github.com/starwing/lua-protobuf
hererocks -j 2.0 -rlatest .
bin/luarocks make lua-protobuf/rockspecs/lua-protobuf-scm-1.rockspec CFLAGS="-fPIC -Wall -Wextra" LIBFLAGS="-shared"
cp protoc.lua pb.so ..
```

**Comment by starwing** [comment]
I will keep this open until I have to to update the docs.

**Comment by rucuriousyet** [comment]
Fair enough

**Comment by starwing** [comment]
readme updaed
