### ISSUE TITLE
import出错，message中的field丢失了

### ISSUE THREAD

**Issue by yiyucyp** [starwing/lua-protobuf#41]
local pb     = require "pb"
local pbio   = require "pb.io"
local buffer = require "pb.buffer"
local slice  = require "pb.slice"
local conv   = require "pb.conv"
local protoc = require "protoc".new()
protoc.paths[#protoc.paths+1]="./protobuf3"

protoc:loadfile("protocol.proto")
print(pb.type("login_test"))
print(pb.type("protocol.C2S"))

for field, number in pb.fields("protocol.C2S") do
    print(field, number)
end

for field, number in pb.fields("protocol.S2C") do
    --print(field, number, "\n")
    print(field, number)
end

1、加载附件中的文件时，在S2C中找不到res_change这个field，打印不出来
2、在protoc中调试跟踪是有这个field的，但是pb.load后没有了

[Protobuf3.zip](https://github.com/starwing/lua-protobuf/files/1792170/Protobuf3.zip)

**Comment by starwing** [comment]
protoc目前不是自动载入import文件的，你需要手动载入所有import的文件，这和protoc的语义是一致的，如果希望自动载入import的文件，在loadfile之前先设置`p.include_imports = true`，protoc也有这个选项的

**Comment by yiyucyp** [comment]
不好意思，确实需要设置include_imports才行
