### ISSUE TITLE
pb_nextentry 有bug

### ISSUE THREAD

**Issue by yiyucyp** [starwing/lua-protobuf#42]
PB_API int pb_nextentry(pb_Table *t, pb_Entry **pentry) {
    size_t i = *pentry ? pbT_offset(*pentry, t->hash) : 0;
    size_t size = t->size*t->entry_size;
    while (i += t->entry_size, i < size) {
        pb_Entry *entry = pbT_index(t->hash, i);
        if (entry->key != 0) {
            *pentry = entry;
            return 1;
        }
    }
    *pentry = NULL;
    return 0;
}

如果*pentry为null，i=0时数据获取不到，进入到while的第一次时i会加上t->entry_size，所以如果number为8的标记，会找不到

**Comment by starwing** [comment]
已经修掉了，谢谢报告~
