### ISSUE TITLE
type 和 filed重名时，就会找不到type

### ISSUE THREAD

**Issue by yiyucyp** [starwing/lua-protobuf#45]
message test_type
{
    int r = 1;
}

message type2
{
    test_teype test_type = 1;//当field的名字也叫test_type时就会找不到，内部只有一个nametable
}

**Comment by starwing** [comment]
我目前没发现问题，是不是你test_type拼错了？上面拼的是test_teype，这是我的测试代码：

```lua
local pb = require "pb"
local protoc = require "protoc"

protoc:load [[
message test_type
{
   optional int32 r = 1;
}

message type2
{
   optional test_type test_type = 1;//当field的名字也叫test_type时就会找不到，内部只有一个nametable
}
]]

local chunk = assert(pb.encode("type2", { test_type = { r=1 } }))
print(pb.tohex(chunk))
local t = assert(pb.decode("type2", chunk))
print(require "serpent".block(t))

```

**Comment by yiyucyp** [comment]
pb.encode("test_type", {r=1})--这个时候会出错，因为test_type在lpb_checkname()中是会存在的，但是在pb_type中存的是.test_type

static pb_Type *lpb_checktype(lua_State *L, int idx)
{ return pb_type(default_state(L), lpb_checkname(L, idx)); }
