### ISSUE TITLE
uint32 field coredump

### ISSUE THREAD

**Issue by chamzzzzzz** [starwing/lua-protobuf#5]
message testmessage
{
	optional string account = 1;
	optional string password = 2;
	optional uint32 deviceid = 3;
	optional string test = 4;
}

uint32 changed to int32 is ok..

![image](https://user-images.githubusercontent.com/1501426/27118837-1dae4e20-5118-11e7-957a-7edd06551a1c.png)

**Comment by starwing** [comment]
New version has better coverage and as a full rewritten should resolve all older issues.
