### ISSUE TITLE
allow_alias 选项处理（不检查value 相同项）

### ISSUE THREAD

**Issue by jj4jj** [starwing/lua-protobuf#52]
https://github.com/starwing/lua-protobuf/blob/dcff4c94faaaac3f391b742419f3f37e3b7ca963/protoc.lua#L845

if info.options and info.options.options and info.options.options.allow_alias then
     --nothing  todo skip check enum value uniq
else
    check_dup(self, lex, 'enum number', numbers, 'number', v)
end

**Comment by starwing** [comment]
okay, merged.
