### ISSUE TITLE
关于Message repeated int32 int64的数据解析错误问题

### ISSUE THREAD

**Issue by getong** [starwing/lua-protobuf#54]
see [cloudwu/pbc #114](https://github.com/cloudwu/pbc/issues/114)
只想了解，这个类库有没有这个问题。我们也遇到这个问题，没有找到解决方法。

**Comment by getong** [comment]
可以使用，没有问题。

**Comment by machackx** [comment]
@getong @starwing  这个问题你们怎么解决的？看了一下 repeat int32 解析 pbc的库里的确有问题，直接存了那个int的偏移

**Comment by getong** [comment]
我们迁移使用 starwing/lua-protobuf 了

**Comment by machackx** [comment]
多谢回复， 这个库的效率和稳定性相比云风的pbc如何?@getong

**Comment by getong** [comment]
@machackx 刚开始迁移使用，效果暂时看起来不错。

**Comment by CoolYsl** [comment]
在protobuf文件中的repeated int32 int64字段后面添加 [packed=true]
eg:  repeated int32 id= 1 [packed=true];
