### ISSUE TITLE
Broken encoding of *int64 types in certain Lua environments.

### ISSUE THREAD

**Issue by Enfernuz** [starwing/lua-protobuf#58]
Thanks for the library, really saves the day.

I've been trying to use it on `Lua 5.1` (on Windows) and with the example in README I got this:
```
10 12 0A 04 69 6C 73 65 22 12 0A 05 61 6C 69 63 65 10 F2 D5 FD EE FD FF FF FF FF 01 22 10 0A 03 62 6F 62 10 C7 F0 C6 85 FA FF FF FF FF 01
{
  age = 18,
  contacts = { {
      name = "alice",
      phonenumber = -572560654
    }, {
      name = "bob",
      phonenumber = -1598965689
    } },
  name = "ilse"
}
```
The phone numbers are messed up, as you might have noticed.

When run on `Lua 5.3` (yes, I have built two separate `pb.dll` for different Lua versions), the output is OK.

```
22 0D 0A 05 61 6C 69 63 65 10 F2 D5 FD EE 2D 22 0C 0A 03 62 6F 62 10 C7 F0 C6 85 AA 01 0A 04 69 6C 73 65 10 12
{
  age = 18,
  contacts = { {
      name = "alice",
      phonenumber = 12312341234
    }, {
      name = "bob",
      phonenumber = 45645674567
    } },
  name = "ilse"
}
```

What's more confusing is that on another `Lua 5.1` version (it's embedded in a trading software which allows to run Lua scripts) the output is different from the first one:
```
22 12 0A 05 61 6C 69 63 65 10 80 80 80 80 F8 FF FF FF FF 01 22 10 0A 03 62 6F 62 10 80 80 80 80 F8 FF FF FF FF 01 0A 04 69 6C 73 65 10 12
{
  age = 18,
  contacts = { {
      name = "alice",
      phonenumber = -2147483648
    }, {
      name = "bob",
      phonenumber = -2147483648
    } },
  name = "ilse"
}
```

**Comment by Enfernuz** [comment]
It probably has to do with the size of `lua_Integer` on the target Lua interpreter.

In my case, on Lua 5.3: `sizeof(lua_Integer)` = `sizeof(long long)` = `8`, 
whereas on Lua 5.1: `sizeof(lua_Integer)` = `sizeof(ptrdiff_t)` = `4`, 
so the function `lpb_addtype` in `pb.c`:
```C
typedef union lpb_Value {
    pb_SliceExt s[1];
    uint32_t u32;
    uint64_t u64;
    lua_Integer lint;
    lua_Number lnum;
} lpb_Value;
//...
static int lpb_addtype(lua_State *L, pb_Buffer *b, int idx, int type) {
   //...
   lpb_Value v;
   //...
   switch (type) {
      //...
      case PB_Tint64: case PB_Tuint64:
              v.lint = lua_tointegerx(L, idx, &ret);
              if (ret) pb_addvarint64(b, (uint64_t)v.lint);
      break;
      //...
    }
    //...
```
1. reads a 4 byte integer from the Lua state;
2. extends it to `uint64_t` and sends further to the processing.

**Comment by starwing** [comment]
Okay I will hold this situation to see how to solve it.

**Comment by starwing** [comment]
I push a new commit support operate 64bit integers in Lua 5.1 & 5.2 & jit, you could try it out.

**Comment by Enfernuz** [comment]
Unfortunately, it doesn't do the trick.

Here is the environment I've tested it in:
Lua 5.1.5-52 https://github.com/rjpcomputing/luaforwindows/archive/v5.1.5-52.zip (I believe it's for x86, but this is exactly what I need).

I've compiled `pb` against it, ran the test and got the following:
![pb64](https://user-images.githubusercontent.com/935535/40876539-21247ee6-6682-11e8-9fc1-f2c2d4aadc1c.png)

The code of the test:
```lua
local pb = require "pb"
local protoc = require "lua-protobuf.protoc"

assert(protoc:load [[
   message Phone {
      optional string name        = 1;
      optional int64  phonenumber = 2;
   }
   message Person {
      optional string name     = 1;
      optional int32  age      = 2;
      optional string address  = 3;
      repeated Phone  contacts = 4;
   } ]])

local data = {
   name = "ilse",
   age  = 18,
   contacts = {
      { name = "alice", phonenumber = 12312341234  },
      { name = "bob",   phonenumber = 45645674567 }
   }
}

local bytes = assert(pb.encode("Person", data))
print(pb.tohex(bytes))

local data2 = assert(pb.decode("Person", bytes))
print(require "lua-protobuf.serpent".block(data2))
```

**Comment by Enfernuz** [comment]
By the way, the new option doesn't help either:
```lua
local pb = require "pb"
local protoc = require "lua-protobuf.protoc"
pb.option("int64_as_number")
...
```

![pb64_1](https://user-images.githubusercontent.com/935535/40877211-880304b8-6685-11e8-93d1-3eeaf52fbcc9.png)

**Comment by starwing** [comment]
Thanks for the information. But I can't access a win32 machine now. I will find a win32 machine and try to see how to fix it :-(

**Comment by Enfernuz** [comment]
You don't have to do it on an x86 system. I have an x64 one  -- it just happens that the Lua environment I have to use must be the one that is compiled for win32.

**Comment by starwing** [comment]
@Enfernuz In your case the phonenumber is already bigger than 32bit integer, so the correct way to do this is:
```lua
local data = {
   name = "ilse",
   age  = 18,
   contacts = {
      { name = "alice", phonenumber = '#12312341234'  },
      { name = "bob",   phonenumber = '#45645674567' }
   }
}
```

**Comment by starwing** [comment]
I have found a Win32 machine and fix the issue, could you try for the lastest commit?

**Comment by Enfernuz** [comment]
Yep, works like a charm. Thank you!
```lua
local pb = require "pb"
local protoc = require "lua-protobuf.protoc"

assert(protoc:load [[
   message Phone {
      optional string name        = 1;
      optional int64  phonenumber = 2;
   }
   message Person {
      optional string name     = 1;
      optional int32  age      = 2;
      optional string address  = 3;
      repeated Phone  contacts = 4;
   } ]])

local data = {
   name = "ilse",
   age  = 18,
   contacts = {
      { name = "alice", phonenumber = 12312341234  },
      { name = "bob",   phonenumber = 45645674567 }
   }
}

local bytes = assert(pb.encode("Person", data))
print(pb.tohex(bytes))

local data2 = assert(pb.decode("Person", bytes))
print(require "lua-protobuf.serpent".block(data2))
```
![pb64_2](https://user-images.githubusercontent.com/935535/40879411-0d3dd5a0-66a8-11e8-8209-e10b5069ea0c.png)
