### ISSUE TITLE
请问是否支持在一个proto中import其他proto？

### ISSUE THREAD

**Issue by imzoer** [starwing/lua-protobuf#64]
message 定义在不同的proto中

**Comment by imzoer** [comment]
![image](https://user-images.githubusercontent.com/3349154/44035479-30c70474-9f42-11e8-922f-5f9cf8a0f47d.png)

**Comment by imzoer** [comment]
如果能正确处理 proto 中的 import应该也是满足需求的

**Comment by imzoer** [comment]
补充：目前用的是 old 分支的代码

**Comment by ifshuaishuai** [comment]
这里写一下import的使用吧，耗费一上午爬代码发现的，造福一下后来者
1. load函数第二个参数可以指定 protoName，protoc:load(protoContent, protoName)
2. 加载的顺序需要保证被 import的先导入。
综上，需要先对proto文件进行拓扑排序，然后load指定 protoName即可

**Comment by starwing** [comment]
另外，记得要用protoc.new()，请存下parser对象编译器实例，然后按照拓扑顺序去load。现在不能够protoc:load了，因为这样每次都是全新的编译器实例。

或者，使用（没有文档标出的）loadfile，可以设置path来指定载入地址~
