### ISSUE TITLE
Encoder misses out oneof fields with default values.

### ISSUE THREAD

**Issue by edam** [starwing/lua-protobuf#73]
With this:

    message Test {
        oneof test {
            uint64 foo = 1;
            string bar = 2;
        }
    }

The encoder gives some odd results when default values are used...

    lua> dump( pb.encode( 'Test', { foo = 1 } ) )
    "\b\x01"
    lua> dump( pb.encode( 'Test', { foo = 0 } ) )
    ""

For default values (the second case), this is not the same as the commandline protobuf compiler, `protoc`, generates:

    $ echo 'foo: 1' | protoc --encode=Test test.proto | hexdump
    00000000  08 01                                       |....|
    00000002
    $ echo 'foo: 0' | protoc --encode=Test test.proto | hexdump
    00000000  08 00                                       |....|
    00000002

**Comment by starwing** [comment]
Yes, the `one of` support is in-complete. pr are welcome. Or I will take time to see how to solve these issues... :-(

**Comment by starwing** [comment]
I have fixed these issues, you may check out the head and any feedbacks are welcome

**Comment by edam** [comment]
Seems to fix the issue for me! 👍
