### ISSUE TITLE
lightweight way of decode/encode without passing all data to lua

### ISSUE THREAD

**Issue by bjne** [starwing/lua-protobuf#79]
It would be nice to be able to do the following to allow for a faster way of working with
protobuf from lua, avoiding the overhead of constructing tables and so on:

```lua
local msg = pb.decode('message',  data, true)
assert(type(msg) == 'userdata')
msg.some_string = 'new string'

msg:encode()
```

**Comment by starwing** [comment]
it need a anthoer quite different imeplement and may be hard to get it work in current implememnt :-(
