### ISSUE TITLE
'oneof' not supported; presence of 'oneof' may make other types inaccessible

### ISSUE THREAD

**Issue by seabadger** [starwing/lua-protobuf#8]
When using a type that uses 'oneof', the type is not found.
As far as I can tell, the 'oneof' is not even processed by this library, so I suspect this is not currently supported.

**Comment by seabadger** [comment]
The behavior in the presence of types containing 'oneof' is actually quite bad. If a protobuf definition file (generated by protoc from the IDL) happens to contain a type with a set of 'oneof' fields, any types that occur after this type in the same file seem to be invisible to this library (I suspect that somehow the file winds up being misparsed)

**Comment by starwing** [comment]
Now oneof and map are support, but how to make oneof sematics in Lua?

**Comment by tkroman** [comment]
@starwing if i can make a suggestion, something like this would be nice:

```
message X { int32 x = 1 }
message Y { string s = 1 }
message O { oneof xOrS = { X thisIsX = 1; Y thisIsY = 2 } }
```

so in lua:

```
o = { xOrS = { thisIsX = { x = 1 } } }
```

would represent a valid `O` message.

Is that what you meant by Lua semantics?

**Comment by seabadger** [comment]
I think the issue that @starwing is referring to is that 'oneof' semantics are supposed to reject messages that have more than one member of the oneof field set. Unlike the C++ protobuf API, you don't have validating accessors here, but a passive table object, so any validation has to be deferred.

Assuming I understood correctly,I can think of two approaches:
  - validate at encode time (optionally). Not sure of the performance implications of this.
  - provide a separate validation routine that can be called if the user wants. It could
     enforce various protobuf rules that are currently ignored, including some or all of the following:
     - 'oneof' mutual exclusion
     - 'required' (for proto2)
     - enumeration constraints:
        -  'reserved', 'reserved_range', 'deprecated' directives
         - aliasing allowed only  if 'allow_alias' is specified
     - can detect unknown keys in table (those not matching any fields in the type)
     - can detect out-of-range numeric values (e.g., signed values for unsigned fields, 64-bit values for 32-bit fields)


(there could also be a similar routine on the decode side, for, e.g., populating proto2 and proto3 default values)

**Comment by starwing** [comment]
@tkroman Yes, that's a possible implement.  But the oneof name may the same with other fields name, so maybe we cannot do that.  Do you have some infromations about "oneof name must not duplicate with field name" in google's specs? Thanks for the advice :-)

**Comment by starwing** [comment]
@seabadger Good advice! It's indeed a good way to implement these constraints. But implements they are complex in C code. So maybe add a new Lua module named e.g. pb.validate.lua is better.

I have try this way when I have time :-)

**Comment by seabadger** [comment]
regarding the oneof semantics -- I'm pretty sure the 'oneof' is just an added constraint to fields, you cannot have the same field name inside and outside of a 'oneof'. I.e.,
'''
   message Foo {
     oneof exclusion1 {
        int foo = 1;
        string bar = 2;
     }
     int foo = 3; // this should not work as this duplicates the name of field 1
}
'''
This should be easy to check by seeing if protoc accepts the above type
(I can check tomorrow, don't have access to protoc right now).

**Comment by tkroman** [comment]
@seabadger @starwing if `oneof` fields are nested under the corresponding field, I don't think the name clash is possible. e.g. in your example:

```
message Foo {
  oneof exclusion1 {
    int foo = 1;
    string bar = 2;
  }
  int foo = 3;
}
```

Lua's table repr would be this:

```
oneOfInt = {
  exclusion1 = {
    foo = 123
  },
  foo = 42
}
```

and

```
oneOfString = {
  exclusion1 = {
    bar = 'abc'
  },
  foo = 42
}
```

**Comment by seabadger** [comment]
The name clash is not possible in principle. The name of the OneOf  is the
name if a *constraint*over a set of fields, which otherwise behave as if
they  were declared outside of the OneOf.   The oneof name is only used for
constraint checks. The fields themselves are not nested under another
structure, and I think introducing such an extra level of nesting  is both
unnecessary and inconsistent with how other language bindings work (e.g.
C++).

On Feb 12, 2018 4:20 AM, "Roman Tkalenko" <notifications@github.com> wrote:

@seabadger <https://github.com/seabadger> @starwing
<https://github.com/starwing> if oneof fields are nested under the
corresponding field, I don't think the name clash is possible. e.g. in your
example:

message Foo {
  oneof exclusion1 {
    int foo = 1;
    string bar = 2;
  }
  int foo = 3;
}

Lua's table repr would be this:

oneOfInt = {
  exclusion1 = {
    foo = 123
  },
  foo = 42
}

and

oneOfString = {
  exclusion1 = {
    bar = 'abc'
  },
  foo = 42
}

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/starwing/lua-protobuf/issues/8#issuecomment-364866937>,
or mute the thread

**Comment by starwing** [comment]
@seabadger @tkroman what I mean is like this:
message Foo {
  oneof baz {
     int foo = 1;
     int bar = 2;
  }
  int baz = 3;
}

notice the oneof constraint name "baz" has the same name as the field "baz", so you can not both specific the baz field and the baz nested table.
