### ISSUE TITLE
when i decode a message which contains a "oneof" syntactic raise a error called "un-finished bytes (len 1 at offset 7)"

### ISSUE THREAD

**Issue by clear-love** [starwing/lua-protobuf#81]
i have a message like this:
![image](https://user-images.githubusercontent.com/28770497/48935034-2b1c7c80-ef41-11e8-9f6a-311e4b5988b5.png)

when a give the filed "specific_data" a value which message is like this 
![image](https://user-images.githubusercontent.com/28770497/48935189-b5fd7700-ef41-11e8-84b5-380ec08a5131.png)
:
then when i decode this message in client it raise a error message like this:un-finished bytes (len 1 at offset 7),but when i use the  interger type int32 to replace the interger type int64, it goesed true, i dont know the reason what caused this result

**Comment by starwing** [comment]
maybe your server protocol use int32? could you give me a binary message (output of `pb.tohex`) to let me help you see what's wrong in the message?
