### ISSUE TITLE
undefined symbol: luaL_prepbuffer

### ISSUE THREAD

**Issue by CatCodeMe** [starwing/lua-protobuf#83]
#issue
- 云主机默认环境安装的是Lua5.1，使用测试样例时，pb.so文件会出现undefined symbol
- 我又重新安装了lua5.3, **并且把编译生成的 pb.so 文件，手动copy到 lua5.3的lib库下**，出现了如下问题
![image](https://user-images.githubusercontent.com/11496772/49720745-8a95be80-fc9b-11e8-90b3-61e1fa8b07ca.png)

**Comment by DrTF** [comment]
根据知乎中文说明，编写的aa.lua

**Comment by DrTF** [comment]
使用gcc安装已成功

**Comment by starwing** [comment]
Lua不同大版本二进制是不兼容的

**Comment by DrTF** [comment]
大佬，我发现原因了。
- 测试环境是 lua 5.1.5 , luaRocks  2.4.3

1. 当我使用 `luarocks install  lua-protobuf`安装时, 
   - 在 `/usr/local/share/lua/5.1/` 生成 `protoc.lua` 源文件
   - 在`/usr/local/lib/lua/5.1/` 生成 `pb.so`源文件
   - 这种方式下，引用`pb.so`会报错, 
     - e.g.   `./pb.so: undefined symbol: lua_tointegerx`, 这个好像就是因为lua版本的问题
2. 但是当我使用 README文档 `gcc -O2 xxxxxx` **手动编译**生成 `pb.so`文件，此时引用不会有问题
   -  我目前只使用了`encode`，`decode`，没有遇到问题
3. 我对比了一下两版`pb.so`文件的md5，竟然**不一样**。所以我怀疑是不是luarock的锅。

**Comment by starwing** [comment]
你luarocks使用的lua可能和系统安装的不一样，你查询一下luarocks（应该有类似info的命令）使用的Lua到底是装在哪儿的
