### ISSUE TITLE
bytes expected for type message, got varint"  

### ISSUE THREAD

**Issue by kicasstt** [starwing/lua-protobuf#86]
"lib/robot.lua:127: type mismatch at offset 665, bytes expected for type message, got varint"
用老版本的lua-protobuf,解析bytes的时候返回number,用最新的就报此错，求大神看下
如果不能角色，咋容错啊

**Comment by starwing** [comment]
你schema写错了？bytes就应该是字符串啊

**Comment by Missmiaom** [comment]
我也出这个问题了，而且是特定的消息，数据只有33字节，但是报错提示 varint value at offset 34

**Comment by fiberCorpertor** [comment]
请问这个问题深层次的原因是什么？？ 我这边好多协议都报一样的错误，急求，谢谢啊

**Comment by jiafeimao357** [comment]
> 你schema写错了？bytes就应该是字符串啊

我也是报这个错误，请问是什么原因导致的？type mismatch for field 'TSTypes' at offset 104, bytes expected for type message, got varint

**Comment by starwing** [comment]
一般是proto写错了，或者v2 v3版本不匹配，或者packed有问题。另外老版本的可能有bug，建议升级。最新的版本很稳定了

**Comment by fiberCorpertor** [comment]
其实就是协议没有对上导致的
