### ISSUE TITLE
Could you deal custom options

### ISSUE THREAD

**Issue by SheepQi** [starwing/lua-protobuf#88]
When I defining a message like this:
```
import "google/protobuf/descriptor.proto";

extend google.protobuf.MessageOptions {
  optional string my_option = 51234;
}

message MyMessage {
  option (my_option) = "Hello world!";
}
```
I have no way to get my_option's value.
Thank you!

**Comment by starwing** [comment]
you should load `descriptor.proto` from Google and decode your pb file as `google.protobuf.DescriptorFileSet` and get options.

**Comment by stillcold** [comment]
我还是没有完全理解，有更具体一点的例子吗？

**Comment by stillcold** [comment]
因为我这么操作了之后，发现options是一张空表
