### ISSUE TITLE
aliased enums not fully supported, cause a crash

### ISSUE THREAD

**Issue by seabadger** [starwing/lua-protobuf#9]
using an enum such as the following:
```
enum AliasedEnum {
    option allow_alias = true;
    ZERO = 0;
    ONE = 1;
    TWO = 2;
    FIRST = 1;
  }
```
is problematic. Using non-aliased enum members works fine. Using "FIRST" above works fine as well. Using "ONE" (which FIRST is aliased to) crashes the library. I've not tried multiple aliases, or determined the exact behavior (superficially it seems that the last member using a given value seems to work, and earlier ones don't; this needs to be confirmed).

**Comment by starwing** [comment]
New version has better coverage and as a full rewritten should resolve all older issues.
