### ISSUE TITLE
大量调用的时候出现解码异常，使用的当前master版本，看看能否发现些问题

### ISSUE THREAD

**Issue by fatihwk** [starwing/lua-protobuf#92]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `./bin/starve'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00000000005ee024 in luaH_getstr (t=0x7f95fe2caa20, key=0x7f9624009a40)
    at /home/arthur/work/starveserver/opt/luapb/lua/ltable.c:525
525         if (ttisshrstring(k) && eqshrstr(tsvalue(k), key))
[Current thread is 1 (Thread 0x7f9631ffb700 (LWP 69028))]
Missing separate debuginfos, use: debuginfo-install glibc-2.17-260.el7_6.3.x86_64 keyutils-libs-1.5.8-3.el7.x86_64 krb5-libs-1.15.1-37.el7_6.x86_64 libcom_err-1.42.9-13.el7.x86_64 libgcc-4.8.5-36.el7_6.1.x86_64 libselinux-2.5-14.1.el7.x86_64 libstdc++-4.8.5-36.el7_6.1.x86_64 ncurses-libs-5.9-14.20130511.el7_4.x86_64 openssl-libs-1.0.2k-16.el7_6.1.x86_64 pcre-8.32-17.el7.x86_64 readline-6.2-10.el7.x86_64 zlib-1.2.7-18.el7.x86_64
(gdb) bt
#0  0x00000000005ee024 in luaH_getstr (t=0x7f95fe2caa20, key=0x7f9624009a40)
    at /home/arthur/work/starveserver/opt/luapb/lua/ltable.c:525
#1  0x00000000005ee0b8 in luaH_get (t=0x7f95fe2caa20, key=0x7f9581171610)
    at /home/arthur/work/starveserver/opt/luapb/lua/ltable.c:542
#2  0x00000000005ee1a2 in luaH_set (L=0x7f9624001078, t=0x7f95fe2caa20, key=0x7f9581171610)
    at /home/arthur/work/starveserver/opt/luapb/lua/ltable.c:573
#3  0x00000000005d3619 in lua_rawset (L=0x7f9624001078, idx=-3) at /home/arthur/work/starveserver/opt/luapb/lua/lapi.c:777
#4  0x00007f96305f3a1b in lpb_decode (e=0x7f9631ff9c00, t=0x7f9624032fc8)
    at /home/arthur/work/starveserver/opt/luapb/lua-protobuf/pb.c:1676
#5  0x00007f96305f3b44 in lpb_decode_ex (L=0x7f9624001078, s=...)
    at /home/arthur/work/starveserver/opt/luapb/lua-protobuf/pb.c:1693
#6  0x00007f96305f3bd2 in Lpb_decode (L=0x7f9624001078) at /home/arthur/work/starveserver/opt/luapb/lua-protobuf/pb.c:1699
#7  0x00000000005d9277 in luaD_precall (L=0x7f9624001078, func=0x7f95811715e0, nresults=-1)
    at /home/arthur/work/starveserver/opt/luapb/lua/ldo.c:337
#8  0x00000000005f4ff2 in luaV_execute (L=0x7f9624001078) at /home/arthur/work/starveserver/opt/luapb/lua/lvm.c:991
#9  0x00000000005d972d in luaD_call (L=0x7f9624001078, func=0x7f9581171540, nResults=-1, allowyield=0)
    at /home/arthur/work/starveserver/opt/luapb/lua/ldo.c:422
#10 0x00000000005d3c0d in f_call (L=0x7f9624001078, ud=0x7f9631ffa490)
    at /home/arthur/work/starveserver/opt/luapb/lua/lapi.c:914
#11 0x00000000005d88f4 in luaD_rawrunprotected (L=0x7f9624001078, f=0x5d3bd6 <f_call>, ud=0x7f9631ffa490)
    at /home/arthur/work/starveserver/opt/luapb/lua/ldo.c:142
#12 0x00000000005d9ec8 in luaD_pcall (L=0x7f9624001078, func=0x5d3bd6 <f_call>, u=0x7f9631ffa490, old_top=32, ef=16)
    at /home/arthur/work/starveserver/opt/luapb/lua/ldo.c:644
#13 0x00000000005d3cdc in lua_pcallk (L=0x7f9624001078, nargs=4, nresults=-1, errfunc=1, ctx=0, k=0x0)
    at /home/arthur/work/starveserver/opt/luapb/lua/lapi.c:940
#14 0x0000000000593bf4 in sol::basic_protected_function<sol::basic_reference<false>, false, sol::basic_reference<false> >::luacall<true> (this=0x7f95fdec4700, argcount=4, resultcount=-1, h=...)
    at /home/arthur/work/starveserver/opt/sol2/sol/protected_function.hpp:53
#15 0x000000000059195c in sol::basic_protected_function<sol::basic_reference<false>, false, sol::basic_reference<false> >::invoke<true>(sol::types<>, std::integer_sequence<unsigned long>, long, sol::detail::protected_handler<true, sol::basic_reference<false> >&) const (this=0x7f95fdec4700, n=4, h=...)
    at /home/arthur/work/starveserver/opt/sol2/sol/protected_function.hpp:98
#16 0x0000000000591380 in sol::basic_protected_function<sol::basic_reference<false>, false, sol::basic_reference<false> >::call<, unsigned long, int, std::string, int>(unsigned long&&, int&&, std::string&&, int&&) const (this=0x7f95fdec4700, 
    args#0=@0x7f9631ffa7b0: 151, args#1=@0x7f9631ffa7ac: 2, args#2=..., args#3=@0x7f9631ffa7a8: 35)
    at /home/arthur/work/starveserver/opt/sol2/sol/protected_function.hpp:274
#17 0x000000000059152c in sol::basic_protected_function<sol::basic_reference<false>, false, sol::basic_reference<false> >::operator()<unsigned long, int, std::string, int> (this=0x7f95fdec4700, args#0=@0x7f9631ffa7b0: 151,

**Comment by starwing** [comment]
没能发现问题，能给一个单个的能（有概率）重现问题的Lua脚本吗？

**Comment by fatihwk** [comment]
应该收到错误的pb包后导致的异常，lua层catch住可以了。 当然程序里做更好的检查可能更好。 谢谢。
