### ISSUE TITLE
uint64 解析出负数

### ISSUE THREAD

**Issue by luckyrainbow** [starwing/lua-protobuf#93]
uint64格式的数值超过 9223372036854775807 解析出来是负数，看起来像只是支持int64。
 (9223372036854775807 ~ 18446744073709551615区间的数都是负值)

**Comment by starwing** [comment]
对，Lua只支持有符号64位数

**Comment by membphis** [comment]
改成用字符串存储吧 囧。。。

**Comment by starwing** [comment]
@membphis 支持字符串存储，只需要设置：
`pb.option "int64_as_string"

即可。
