### ISSUE TITLE
Error on running the sample pb 

### ISSUE THREAD

**Issue by Jevelson** [starwing/lua-protobuf#94]
lua: error loading module 'pb' from file '/usr/lib64/lua/5.1/pb.so':
	/usr/lib64/lua/5.1/pb.so: undefined symbol: luaL_setfuncs

I installed the protobuffer module using luarocks. 

Installed rocks:
----------------

lua-protobuf
   scm-1 (installed) - /usr/lib64/luarocks/rocks

**Comment by Jevelson** [comment]
License: 	MIT
Homepage: 	https://github.com/starwing/lua-protobuf
Installed in: 	/usr

Modules:
	pb (/usr/lib64/lua/5.1/pb.so)
	protoc (/usr/share/lua/5.1/protoc.lua)

**Comment by starwing** [comment]
your luarocks uses a Lua 5.2 for compiling, not 5.1, check the configuration.
