### ISSUE TITLE
Does it support google.protobuf.Any field? and how to use it?

### ISSUE THREAD

**Issue by coheneye** [starwing/lua-protobuf#95]
Thanks in advance.

**Comment by starwing** [comment]
It does support. You should import the proto file from google, and process the decoded result yourself. See documentation in google’s any.proto file.

**Comment by coheneye** [comment]
Suddenly i learned from your tips. I should process raw Any format by myself, right?
but i really don't think it is more intuitive or simpler than the encoded message string field.

**Comment by starwing** [comment]
@coheneye Now you can try the new version and using the `pb.hooks` routine to translate `Any` automatically.
