### ISSUE TITLE
能否在协议解码时，支持对特殊类型用户自定义Lua对象的原表

### ISSUE THREAD

**Issue by cocowolf** [starwing/lua-protobuf#96]
如题，比如proto3协议的Any类型，在解码时插入一个函数，为any对象设置一个原表，包含pack unpack  isType 函数，这样可以直接访问这几个函数为来判断any对象的类型和解析any到具体的类型。

比如pb能否支持一个注册函数，针对不同的Protobuf消息类型，注册不同的原表，在解码是自动设置对象原表。如：
pb.metatable.register("google.protobuf.Any",meta)
pb.metatable.register("tutorial.Person",meta)

比如protobuf的Enum类型，通过这种方式也可以扩展为一个对象
enum Color {  Red = 0;  Green = 1;  Blue = 2; }

local colorMeta  = {}
function colorMeta:name()
    return self.name
end

function colorMeta:value()
    return pb.enum("Color",self.name)
end

pb.metatable.register("Color",colorMeta)

也许以后可以通过自动扫描所有的.proto文件或者.pb文件，自动生成Any、Enum这些类型的原表，然后注册到解码器中。

**Comment by starwing** [comment]
已经实现了hook功能

**Comment by cocowolf** [comment]
谢谢作者 @starwing  的付出，功能很好用！

为方便大家使用，写了个简单的示例：
	pb.option("enable_hooks")
	pb.hook("google.protobuf.Any",function(t)
			local meta = { __classname = "Any",unpack=function(self)
				local name = string.sub(self.type_url,21)
				return pb.decode(name,self.value)
			end}
			meta.__index = meta
			setmetatable(t,meta)
		end)
	
	pb.hook("tutorial.Color",function(t)
			return { name = t,value = pb.enum("tutorial.Color",t) }
		end)
