### ISSUE TITLE
pb unsafe 有 bug

### ISSUE THREAD

**Issue by ifreedom** [starwing/lua-protobuf#97]
在 Lpb_decode_unsafe 中第一个参数是指针，第二个参数是长度，但是在后续调用的 lpb_decode 中，要求的第一个参数是类型（字符串），参数冲突了。

![image](https://user-images.githubusercontent.com/333959/60157315-0cf16480-9821-11e9-8d45-385a9dda6ef2.png)
![image](https://user-images.githubusercontent.com/333959/60157344-1c70ad80-9821-11e9-8ca1-d3a2e5ad5426.png)

**Comment by starwing** [comment]
行，我试着修一下，还有问题就reopen～
